apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-eynn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-eynn
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-eynn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-eynn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-eynn
    spec:
      containers:
      - image: quay.io/pkumari_org/release-dev-eqtz/appstudio/dc-metro-map-eynn@sha256:b29e1a54555f511b93c9ae64e2835f8c7ba01628dd4f4a0758deb8cf3a94d00c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
